feat(flexibleip): add support for flexible ip
scaleway/terraform-provider-scaleway pull request #1022
Opened 2022-01-06 15:12 UTC by remyleone

2022-06-22 07:46 UTC, remyleone commented on docs/resources/flexible_ip.md
> +    os = "96e5f0f2-d216-4de2-8a15-68730d877885"
Could you use: https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/baremetal_os

2022-06-22 07:46 UTC, remyleone commented on scaleway/resource_flexible_ip_test.go
> +							os          = "96e5f0f2-d216-4de2-8a15-68730d877885"
https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/baremetal_os

2022-06-22 07:46 UTC, remyleone commented on scaleway/resource_flexible_ip_test.go
> +// working with an already running baremetal called through data_source,
Probably due to a race condition. It should be fixed on the product side.

2022-06-22 07:46 UTC, remyleone commented on scaleway/resource_flexible_ip_test.go
> +							os          = "96e5f0f2-d216-4de2-8a15-68730d877885"
https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/baremetal_os

2022-07-04 13:53 UTC, remyleone commented on docs/resources/flexible_ip.md
> +    os_id = "03b7f4ba-a6a1-4305-984e-b54fafbf1681"
Could you use an explicit name for os? Not an uuid but something like ubuntu for instance.

2022-07-04 13:53 UTC, remyleone commented on scaleway/data_source_flexible_ip_test.go
> +					resource.TestCheckResourceAttrPair(
Hum could you add also the test that scaleway_flexible_ip.by_address returns also the good UUID?

2022-07-04 13:53 UTC, remyleone commented on scaleway/data_source_flexible_ip_test.go
> +					resource.TestCheckResourceAttrPair(
Hum could you add also the test that scaleway_flexible_ip.by_id returns also the good IP?

2022-07-04 13:53 UTC, remyleone commented on docs/resources/flexible_ip.md
> +    name = "main"
Can you put a really ECDSA key there? So that people can quickly identify where is the key

2022-07-04 13:53 UTC, remyleone commented on docs/resources/flexible_ip.md
> +    offer_id = "25dcf38b-c90c-4b18-97a2-6956e9d1e113"
Is there a way to get this offer using a name that humans can understand?

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +				Description: "The server associated with this flexible IP",
```suggestion
				Description: "The baremetal server associated with this flexible IP",
```

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +				Description: "The date and time of the creation of the Flexible IP",
Could you add the name of the format?

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +				Description: "The date and time of the last update of the Flexible IP",
Could you add the name of the format?

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +	_ = d.Set("zone", zone) // TODO use zone field from flexibleIP when available
Could you fix this TODO?

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +	_ = d.Set("created_at", flexibleIP.CreatedAt.Format(time.RFC3339))
Use flattenTime

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip.go
> +	_ = d.Set("updated_at", flexibleIP.UpdatedAt.Format(time.RFC3339))
Use flattenTime

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip_test.go
> +							os_id = "03b7f4ba-a6a1-4305-984e-b54fafbf1681"
Could you use a human-readable data source for this? With something like ubuntu

2022-07-04 13:53 UTC, remyleone commented on scaleway/resource_flexible_ip_test.go
> +							offer_id = "25dcf38b-c90c-4b18-97a2-6956e9d1e113"
Could you use a human-readable offer ?

2022-07-08 12:31 UTC, remyleone commented on docs/resources/flexible_ip.md
> +- `ip_address` -  The IP address of the Flexible IP
```suggestion
- `ip_address` -  The IPv4 address of the Flexible IP
```

2022-07-08 12:54 UTC, Codelax requested changes

2022-07-11 09:54 UTC, Codelax commented on scaleway/data_source_flexible_ip.go
> +	}
Duplicate of `d.SetId(zoneID)`

2022-07-11 09:56 UTC, Codelax commented on scaleway/data_source_flexible_ip.go
> +	dsSchema["id"] = &schema.Schema{
change to `flexible_ip_id`

2022-07-12 12:35 UTC, Codelax requested changes

2022-07-12 12:35 UTC, Codelax commented on scaleway/resource_flexible_ip.go
> +		},
Missing timeouts

2022-07-12 12:35 UTC, Codelax commented on scaleway/resource_flexible_ip.go
> +	_, err = waitFlexibleIP(ctx, fipAPI, zone, flexibleIP.ID, d.Timeout(schema.TimeoutUpdate))
Use TimeoutCreate

2022-07-12 12:46 UTC, Codelax approved these changes

2022-07-12 12:47 UTC, merged