fix(vpc_gw_dhcp): Properly set fields that should default to true
scaleway/terraform-provider-scaleway pull request #1058
Opened 2022-01-26 10:28 UTC by Tuetuopay

Terraform will make sure that fields not present in the file will be set, so we never send nil to the api and get its defaults. Set the defaults ourselves to be consistent with the docs.

2022-01-26 10:32 UTC, remyleone commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("enable_dynamic is false, should defautl to true")
```suggestion
			return fmt.Errorf("enable_dynamic is false, should default to true")
```

2022-01-26 10:32 UTC, remyleone commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("push_default_route is false, should defautl to true")
```suggestion
			return fmt.Errorf("push_default_route is false, should default to true")
```

2022-01-26 10:32 UTC, remyleone commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("push_dns_server is false, should defautl to true")
```suggestion
			return fmt.Errorf("push_dns_server is false, should default to true")
```

2022-01-26 10:33 UTC, Tuetuopay commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("enable_dynamic is false, should defautl to true")
fixed

2022-01-26 10:33 UTC, Tuetuopay commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("push_dns_server is false, should defautl to true")
fixed

2022-01-26 10:33 UTC, Tuetuopay commented on scaleway/resource_vpc_public_gateway_dhcp_test.go
> +			return fmt.Errorf("push_default_route is false, should defautl to true")
fixed

2022-01-27 10:38 UTC, Monitob submitted a review, later dismissed

2022-01-27 11:25 UTC, Monitob requested changes

2022-01-27 11:25 UTC, Monitob commented on scaleway/resource_vpc_public_gateway_dhcp.go
> +				Default:     true,
This has an impact on the pat-rules test. You should just rerun the test to update the cassettes

2022-01-27 14:37 UTC, merged