feat(obj): add force_destroy option to bucket resource
scaleway/terraform-provider-scaleway pull request #1087
Opened 2022-02-14 15:42 UTC by Codelax

2022-02-15 09:58 UTC, Monitob requested changes

2022-02-15 09:58 UTC, Monitob commented on scaleway/resource_object_bucket.go
> +		err = deleteS3Objects(ctx, s3Client, bucketName)
Hello @Codelax, please consider the versions if there are

2022-02-15 09:58 UTC, Monitob commented on scaleway/resource_object_bucket.go
>  		return diag.FromErr(err)
The delete is a new topic for this resource. Please check if the error is implemented as [here](https://github.com/hashicorp/terraform-provider-aws/blob/26f2311f79416f5d37c439288a7287a3b6a56c26/internal/service/s3/bucket.go#L1288).

2022-02-15 09:58 UTC, Monitob commented on scaleway/resource_object_bucket.go
>  		return diag.FromErr(err)
Please check if bucket exist like [this](https://github.com/hashicorp/terraform-provider-aws/blob/26f2311f79416f5d37c439288a7287a3b6a56c26/internal/service/s3/bucket.go#L1284)

2022-02-15 09:58 UTC, Monitob commented on scaleway/resource_object_bucket.go
> +		err = deleteS3Objects(ctx, s3Client, bucketName)
You can check a similar implementation [here](https://github.com/hashicorp/terraform-provider-aws/blob/26f2311f79416f5d37c439288a7287a3b6a56c26/internal/service/s3/bucket.go#L1305)

2022-02-15 09:58 UTC, Monitob commented on scaleway/helpers_object.go
> +				err = fmt.Errorf("failed to delete S3 object: %s", err)
Add the error definition on the constants with a description

2022-02-15 15:56 UTC, murlock commented on scaleway/testdata/object-bucket-destroy-force.cassette.yaml
> +    url: https://test-acc-scaleway-object-bucket-force-7443382734974225702.s3.fr-par.scw.cloud/
Please use something like `https://test-acc-scaleway-object-bucket-force-7443382734974225702.s3.fr-par.scw.cloud/?versions=`
and response
```
<?xml version="1.0" encoding="UTF-8"?>\n<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>michael-versioning</Name><Prefix></Prefix><KeyMarker></KeyMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><EncodingType>url</EncodingType><IsTruncated>false</IsTruncated><DeleteMarker><Key>magic</Key><VersionId>uLkwWXneH5_gKvlqopQqKZaWhEUVY51m</VersionId><IsLatest>true</IsLatest><LastModified>2021-06-10T14:24:23.000Z</LastModified><Owner><ID>69a360b85b319b998292fbac13803cdc79898d1d2ed0f29f3a245874b0ebd97a</ID></Owner></DeleteMarker><Version><Key>magic</Key><VersionId>vrkAriN1FwpIibUSu9lH9VG65GYp28yB</VersionId><IsLatest>false</IsLatest><LastModified>2021-04-13T14:20:27.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><Owner><ID>69a360b85b319b998292fbac13803cdc79898d1d2ed0f29f3a245874b0ebd97a</ID></Owner><StorageClass>STANDARD</StorageClass></Version></ListVersionsResult>
```

2022-02-15 15:57 UTC, murlock commented on scaleway/testdata/object-bucket-destroy-force.cassette.yaml
> +    url: https://test-acc-scaleway-object-bucket-force-7443382734974225702.s3.fr-par.scw.cloud/test-file
with versioning
`https://michael-versioning.s3.us-east-2.amazonaws.com/toto?versionId=LqBPq9jxroqe.ELbPRg8jq81ey29Zk8t`

2022-03-01 13:19 UTC, Monitob approved these changes

2022-03-01 13:20 UTC, merged