feat(redis): cluster resource
scaleway/terraform-provider-scaleway pull request #1238
Opened 2022-04-25 14:31 UTC by Mia-Cross

2022-04-25 14:56 UTC, Monitob requested changes

2022-04-25 14:56 UTC, Monitob commented on scaleway/resource_redis_cluster.go
> +
Add `waitForRedisCluster` here

2022-04-25 16:00 UTC, remyleone commented on scaleway/resource_redis_cluster.go
> +		Tags:            nil,
If you don't support them, do not specify them. Go will provide the zero values. For Cluster size, acl rules, ...

2022-04-25 16:01 UTC, remyleone commented on scaleway/resource_redis_cluster.go
> +	_ = d.Set("version", cluster.Version)
```suggestion
	_ = d.Set("version", cluster.Version)

```

2022-04-27 12:46 UTC, remyleone submitted a review, later dismissed

2022-04-27 12:49 UTC, Monitob approved these changes

2022-04-27 13:02 UTC, Monitob approved these changes

2022-04-27 13:02 UTC, merged