feat(scaleway_instance_snapshot): volume type unified stg
scaleway/terraform-provider-scaleway pull request #1300
Opened 2022-05-24 21:01 UTC by Monitob

2022-06-28 15:12 UTC, Codelax requested changes

2022-06-29 10:57 UTC, Monitob commented on scaleway/resource_instance_snapshot.go
>  			"type": {
Well done, It is missing on the update. We should be enabled to change `l_ssd` or `b_ssd` to `unified`.

2022-07-01 10:08 UTC, remyleone commented on scaleway/resource_instance_snapshot.go
>  			"type": {
It cannot be changed from what I understood. Maybe we should add a force new

2022-07-13 14:54 UTC, Codelax approved these changes

2022-07-18 08:33 UTC, remyleone approved these changes

2022-07-18 08:33 UTC, merged