feat(iam): add iam ssh key resource
scaleway/terraform-provider-scaleway pull request #1340
Opened 2022-06-23 16:10 UTC by yfodil

2022-06-23 19:06 UTC, remyleone requested changes

2022-06-23 19:06 UTC, remyleone commented on scaleway/provider.go
> +				"scaleway_flexible_ip":                         resourceScalewayFlexibleIP(),
This does not have anything to do with iam. Clean up your commits :)

2022-06-27 12:14 UTC, Codelax commented on scaleway/resource_iam_ssh_key.go
> +			"disabled": {
`disabled` is optional but is not used in resource

2022-07-01 10:40 UTC, Monitob requested changes

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +			Disabled: expandBoolPtr(d.Get("disabled")),
please use the helper `getBool`

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +			"disabled": {
Add a test to set and update this attribute

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +				Optional:    true,
If optional please consider generating a name

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +func resourceScalewayIamSSHKeyRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
Many attributes are missing from the schema. Should the `Fingerprint` be exposed?

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +	res, err := iamAPI.GetSSHKey(&iam.GetSSHKeyRequest{
Please test the terraform import

2022-07-01 10:40 UTC, Monitob commented on scaleway/resource_iam_ssh_key.go
> +	if d.HasChange("disabled") {
Please add a test when the value is null and `true` `false`

2022-07-07 08:45 UTC, merged