feat(object): add object lock configuration resource
scaleway/terraform-provider-scaleway pull request #1566
Opened 2022-11-02 17:17 UTC by quantumsheep

2022-11-04 10:51 UTC, Monitob requested changes

2022-11-04 10:51 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration.go
> +									"years": {
There is a conflict with days and years in the schema

2022-11-04 10:51 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration.go
> +	_, err = conn.ListObjectsWithContext(ctx, &s3.ListObjectsInput{
Not necessary

2022-11-04 10:51 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration.go
> +	_, err = conn.ListObjectsWithContext(ctx, &s3.ListObjectsInput{
Not necessary

2022-11-04 10:51 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration.go
> +		tflog.Debug(ctx, fmt.Sprintf("[WARN] Object Bucket Lock Configuration (%s) not found, removing from state", d.Id()))
Not a debug but a warning

2022-11-04 10:51 UTC, Monitob commented on docs/resources/object_bucket_object_lock_configuration.md
> +        - `mode` - (Required) The default Object Lock retention mode you want to apply to new objects placed in the specified bucket.
Add the supported modes

2022-11-04 13:38 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration.go
> +										ConflictsWith: []string{"rule.default_retention.years"},
```suggestion
										ConflictsWith: []string{"rule.0.default_retention.0.years"},
```

2022-11-04 13:59 UTC, remyleone commented on docs/resources/object_bucket_object_lock_configuration.md
> +        - `mode` - (Required) The default Object Lock retention mode you want to apply to new objects placed in the specified bucket. Valid values are `GOVERNANCE` or `COMPLIANCE`.
What does GOVERNANCE and CONPLIANCE mean in this context?

2022-11-04 13:59 UTC, remyleone commented on docs/resources/object_bucket_object_lock_configuration.md
> +        - `mode` - (Required) The default Object Lock retention mode you want to apply to new objects placed in the specified bucket. Valid values are `GOVERNANCE` or `COMPLIANCE`.
Link to https://www.scaleway.com/en/docs/storage/object/api-cli/object-lock/#retention-modes

2022-11-04 13:59 UTC, remyleone commented on scaleway/resource_object_bucket_lock_configuration.go
> +	objectBucketLockConfigurationRetry = 2 * time.Minute
it seems like a lot

2022-11-10 14:33 UTC, Codelax commented on scaleway/resource_object_bucket.go
> +			return diag.FromErr(fmt.Errorf("couldn't read bucket: %s", err))
use `isS3Error` and define `"ObjectLockConfigurationNotFoundError"` in a constant in `errors_object.go`

2022-11-10 14:33 UTC, Codelax commented on scaleway/resource_object_bucket_lock_configuration.go
> +	if !d.IsNewResource() && ErrCodeEquals(err, s3.ErrCodeNoSuchBucket) {
ErrCodeEquals works with scaleway sdk errors, use `isS3Error`

2022-11-10 14:33 UTC, Codelax commented on scaleway/resource_object_bucket_lock_configuration.go
> +	if ErrCodeEquals(err, s3.ErrCodeNoSuchBucket) {
use object helpers for s3 errors

2022-11-10 14:33 UTC, Codelax commented on scaleway/resource_object_bucket_lock_configuration_test.go
> +	tt := NewTestTools(t)
Do not skip tests with cassettes and init correctly TestTools, defer Cleanup is missing

2022-11-10 15:47 UTC, Codelax commented on scaleway/resource_object_bucket_lock_configuration_test.go
> +func TestAccObjectBucketLockConfiguration_basic(t *testing.T) {
Tests naming does not follow naming of others. Cassettes don't have resource name.

2022-11-10 15:58 UTC, Codelax submitted a review, later dismissed

2022-11-10 16:22 UTC, Monitob requested changes

2022-11-10 16:22 UTC, Monitob commented on scaleway/resource_object_bucket_lock_configuration_test.go
> +					resource.TestCheckResourceAttr(resourceName, "rule.0.default_retention.0.days", "1"),
Please add a test with years

2022-11-10 16:22 UTC, Monitob commented on scaleway/resource_object_bucket.go
> +			"object_lock_enabled": {
Please add this on the bucket documentation

2022-11-10 17:07 UTC, merged