fix(vpc): add resolver for reverse dns
scaleway/terraform-provider-scaleway pull request #1708
Opened 2023-01-20 16:25 UTC by yfodil

2023-01-23 14:16 UTC, remyleone commented on scaleway/helpers_instance.go
> +			} else if slices.Contains(address, res.IP.Address.String()) {
else return slices.Contains(address, res.IP.Address.String())

2023-01-23 14:17 UTC, remyleone commented on scaleway/helpers_vpcgw.go
> +	for {
Could this function be extracted? It is exactly the same logic in both cases?

2023-02-10 10:11 UTC, Codelax requested changes

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_instance_ip_reverse_dns.go
> +			if isInstanceIPReverseResolved(ctx, instanceAPI, reverse.(string), defaultInstanceIPReverseDNSTimeout, res.IP.ID, zone) {
```suggestion
			if isInstanceIPReverseResolved(ctx, instanceAPI, reverse.(string), d.Timeout(schema.TimeoutCreate), res.IP.ID, zone) {
```

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_instance_ip_reverse_dns.go
> +			if isInstanceIPReverseResolved(ctx, instanceAPI, reverse.(string), defaultInstanceIPReverseDNSTimeout, res.IP.ID, zone) {
TimeoutCreate should also be added to the schema

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_instance_ip_reverse_dns.go
> +			if isInstanceIPReverseResolved(ctx, instanceAPI, reverse.(string), defaultInstanceIPReverseDNSTimeout, ID, zone) {
```suggestion
			if isInstanceIPReverseResolved(ctx, instanceAPI, reverse.(string), d.Timeout(schema.TimeoutUpdate), ID, zone) {
```

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_vpc_public_gateway_ip_reverse.go
> +			if isGatewayIPReverseResolved(ctx, vpcgwAPI, reverse, defaultVPCPublicGatewayIPReverseDNSTimeout, res.ID, zone) {
```suggestion
			if isGatewayIPReverseResolved(ctx, vpcgwAPI, reverse, d.Timeout(schema.TimeoutCreate), res.ID, zone) {
```

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_vpc_public_gateway_ip_reverse.go
> +			if isGatewayIPReverseResolved(ctx, vpcgwAPI, reverse, defaultVPCPublicGatewayIPReverseDNSTimeout, ID, zone) {
```suggestion
			if isGatewayIPReverseResolved(ctx, vpcgwAPI, reverse, d.Timeout(schema.TimeoutUpdate), ID, zone) {
```

2023-02-10 10:11 UTC, Codelax commented on scaleway/resource_vpc_public_gateway_ip_reverse.go
> +			Default: schema.DefaultTimeout(defaultVPCPublicGatewayIPReverseDNSTimeout),
```suggestion
			Default: schema.DefaultTimeout(defaultVPCPublicGatewayIPReverseDNSTimeout),
			Create:  schema.DefaultTimeout(defaultVPCPublicGatewayIPReverseDNSTimeout),
			Update:  schema.DefaultTimeout(defaultVPCPublicGatewayIPReverseDNSTimeout),
```

2023-02-13 09:33 UTC, Codelax approved these changes

2023-02-13 15:53 UTC, merged