feat(object): parallelize versions destruction
scaleway/terraform-provider-scaleway pull request #1711
Opened 2023-01-23 15:47 UTC by quantumsheep

Closes #1686

2023-01-27 13:01 UTC, Codelax requested changes

2023-01-27 13:01 UTC, Codelax commented on scaleway/helpers_object.go
> +				deleteMarkerVersionsID := aws.StringValue(deleteMarkerEntry.VersionId)
Same potential concurrency issue

2023-01-30 16:16 UTC, remyleone submitted a review, later dismissed

2023-01-30 16:18 UTC, remyleone approved these changes

2023-01-31 10:26 UTC, Codelax approved these changes

2023-01-31 10:28 UTC, merged