fix(container): replace broken link container documentation
scaleway/terraform-provider-scaleway pull request #1754
Opened 2023-02-06 17:07 UTC by Monitob

2023-02-06 17:14 UTC, quantumsheep requested changes

2023-02-06 17:14 UTC, quantumsheep commented on docs/resources/container_cron.md
> +For more information containers
```suggestion
For more information consult
```

2023-02-07 09:41 UTC, remyleone approved these changes

2023-02-07 09:41 UTC, remyleone approved these changes

2023-02-07 09:42 UTC, quantumsheep approved these changes

2023-02-07 09:43 UTC, merged