feat(k8s): k8s version datasource supports "latest" as a value
scaleway/terraform-provider-scaleway pull request #1809
Opened 2023-02-27 15:12 UTC by Mia-Cross

Closes #1805

NB: the test added in this PR will have to be updated as soon as a new k8s version is available otherwise it will fail.

2023-03-01 13:15 UTC, remyleone commented on scaleway/data_source_k8s_version_test.go
> +					resource.TestCheckResourceAttr("data.scaleway_k8s_version.latest", "name", "1.26.0"),
Could you use testAccScalewayK8SClusterGetLatestK8SVersion or similar function to avoid having hard coded version in your code?

2023-03-02 14:30 UTC, Mia-Cross commented
@remyleone I also added the feature in the doc and improved the way to search for the most recent version as the first one I came up with was only going to work with single digits versions. (Now I use the same as `testAccScalewayK8SClusterGetLatestK8SVersion`)

2023-03-08 09:51 UTC, quantumsheep requested changes

2023-03-08 09:51 UTC, quantumsheep commented on scaleway/data_source_k8s_version.go
> +		}
```suggestion
		if len(res.Versions) == 0 {
			return diag.FromErr(fmt.Errorf("could not find the latest version"))
		}

		version = res.Versions[0]
```

Should never happen but we never know

2023-03-08 10:04 UTC, remyleone approved these changes

2023-03-08 10:24 UTC, merged