docs(review): review of documentation pages
scaleway/terraform-provider-scaleway pull request #2620
Opened 2024-06-18 09:29 UTC by nerda-codes

I have reviewed the documentation pages for:
 
- Block Storage
- Cockpit
- Domains & DNS
- Secret Manager

I explained the different parts in a little bit more detail, and checked the grammar, typos, etc.

I haven't changed anything related to technical information.

2024-08-13 15:16 UTC, Laure-di requested changes

2024-08-13 15:16 UTC, Laure-di commented on docs/data-sources/secret_version.md
> +- `data` - The data payload of the secret version. This is a sensitive attribute containing the secret value. Learn more in the [data section](#data).
`- `data` - The data payload of the secret version. This is a sensitive attribute containing the secret value. Learn more in the [data section](#data-information)`

2024-08-13 15:16 UTC, Laure-di commented on docs/data-sources/secret_version.md
> +- `data` - The data payload of the secret version. This is a sensitive attribute containing the secret value. Learn more in the [data section](#data).
This should fix the pipeline :)

2024-08-13 15:18 UTC, nerda-codes commented on docs/data-sources/secret_version.md
> +- `data` - The data payload of the secret version. This is a sensitive attribute containing the secret value. Learn more in the [data section](#data).
```suggestion
- `data` - The data payload of the secret version. This is a sensitive attribute containing the secret value. Learn more in the [data section](#data-information).
```

2024-08-13 15:20 UTC, Laure-di approved these changes

2024-08-13 15:20 UTC, nerda-codes commented on docs/resources/secret_version.md
> +- `data` - (Required) The data payload of the secret version. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Find out more on the [data section](#data).
```suggestion
- `data` - (Required) The data payload of the secret version. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Find out more on the [data section](#data-information).
```

2024-08-29 13:46 UTC, remyleone approved these changes

2024-08-29 13:47 UTC, remyleone approved these changes

2024-08-29 13:51 UTC, merged