chore: add support for golangci-lint
scaleway/terraform-provider-scaleway pull request #547
Opened 2020-09-16 09:07 UTC by remyleone

2020-09-29 10:35 UTC, jerome-quere requested changes

2020-09-29 10:35 UTC, jerome-quere commented on scaleway/resource_object_bucket.go
> +			l.Errorf("Couldn't update bucket tags: %s", err)
returning the error should be enough as it will be logged upper in the stack.

2020-09-30 12:46 UTC, kindermoumoute approved these changes
LGTM.

2020-09-30 14:02 UTC, jerome-quere approved these changes

2020-09-30 14:03 UTC, merged