chore(ci): add support for nightly acceptance tests
scaleway/terraform-provider-scaleway pull request #565
Opened 2020-09-18 12:09 UTC by remyleone

2020-10-01 13:03 UTC, QuentinBrosse approved these changes
Some NITs

2020-10-01 13:03 UTC, QuentinBrosse commented on .github/workflows/nightly.yml
> +          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
nit
```suggestion
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
```

2020-10-01 13:03 UTC, QuentinBrosse commented on .github/workflows/nightly.yml
> +      - name: Acceptance Tests
nit
```suggestion
      - name: Run Acceptance Tests
```

2020-10-01 13:03 UTC, QuentinBrosse commented on .github/workflows/nightly.yml
> +name: nightly acceptance tests
nit
```suggestion
name: Nightly Acceptance Tests
```

2020-10-05 09:35 UTC, QuentinBrosse approved these changes
LGTM

2020-10-05 09:46 UTC, jerome-quere requested changes

2020-10-05 09:46 UTC, jerome-quere commented on .github/workflows/nightly.yml
> +          fetch-depth: 2
why 2 ?

2020-10-05 09:46 UTC, jerome-quere commented on scaleway/resource_lb_ip_beta.go
> +	err = d.Set("region", string(region))
We ignore `Set` error everywhere else why change here ?

2020-10-05 16:24 UTC, jerome-quere requested changes

2020-10-05 16:24 UTC, jerome-quere commented on scaleway/resource_lb_certificate_beta.go
> +	_ = d.Set("subject_alternative_name", strings.Join(res.SubjectAlternativeName, " "))
subject_alternative_name sould be a list of string not a string

2020-11-02 12:04 UTC, jerome-quere approved these changes

2020-11-02 12:24 UTC, merged