feat(registry): add support for project in namespace
scaleway/terraform-provider-scaleway pull request #607
Opened 2020-10-07 12:08 UTC by remyleone

2020-10-07 12:10 UTC, Sh4d1 requested changes
Let's wait, it's not deployed yet

2020-10-07 13:01 UTC, jerome-quere approved these changes

2020-12-09 10:06 UTC, QuentinBrosse commented on docs/resources/registry_namespace.md
> +- `project_id` - (Defaults to [provider](../index.md#project_id) `project_id`) The ID of the project the registry is associated with.
NIT: in the data-source, you use `registry` and in the resource your use `registry`, we should choose one word.

2020-12-09 10:18 UTC, QuentinBrosse submitted a review, later dismissed
LGTM

2020-12-09 10:26 UTC, Sh4d1 requested changes

2020-12-09 10:26 UTC, Sh4d1 commented on scaleway/resource_registry_namespace.go
> -	// Once it does, use ProjectID instead or OrganizationID
set project id -> project id and org id -> org id

2020-12-09 10:35 UTC, Sh4d1 approved these changes
LGTM

2020-12-09 10:35 UTC, merged