feat(instance): add support for bootscript
scaleway/terraform-provider-scaleway pull request #652
Opened 2020-10-21 13:46 UTC by remyleone

2020-10-21 14:12 UTC, kindermoumoute requested changes

2020-10-21 14:12 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
> +			"bootscript": {
bootscript_id

2020-10-21 14:12 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
>  				Description: "The boot type of the server",
add default value

2020-10-21 14:12 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
> +	if bootType, ok := d.GetOk("boot_type"); ok && bootType == "bootscript" {
[use bootType const](https://github.com/scaleway/scaleway-sdk-go/blob/3c87d958dd1172db3151d8fdbbb51eb309b1bd32/api/instance/v1/instance_sdk.go#L92)

2020-10-21 14:27 UTC, Sh4d1 commented on scaleway/resource_instance_server.go
>  				Description: "The boot type of the server",
maybe add the allowed values too ?

2020-10-21 14:28 UTC, Sh4d1 commented
What happens when a user specifies a bootscript without changing the boot type ? We could either throw an error, or change the boot type.

2020-10-21 17:49 UTC, kindermoumoute requested changes

2020-10-21 17:49 UTC, kindermoumoute commented on docs/resources/instance_server.md
> +- `bootscript` - The ID of the bootscript to use  (set boot_type to `bootscript`).
bootscript_id

2020-10-21 20:35 UTC, Sh4d1 requested changes
Need to set the bootype in create req event when no bootscript

Some questions:
- what about the update?
- what if the user sets the boot_type to local and a bootscript ID ? The states will mismatch, I think throwing an error would be better

2020-10-21 21:05 UTC, NoSuchCommand commented
> Need to set the bootype in create req event when no bootscript
> 
> Some questions:
> 
>     * what about the update?
> 
>     * what if the user sets the boot_type to local and a bootscript ID ? The states will mismatch, I think throwing an error would be better

2020-10-26 13:50 UTC, kindermoumoute requested changes

2020-10-26 13:50 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
> +		b := instance.BootTypeBootscript
IIRC a bootscript can be run in rescue mode too, that's why you should read `boot_type` attribute too

2020-10-26 14:27 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
> +		bootType, ok := bootType.(instance.BootType)
I think you mean `bootType := instance.BootType(bootType.(string))`

2020-10-26 14:31 UTC, kindermoumoute commented on scaleway/resource_instance_server.go
> +		bootType, ok := bootType.(instance.BootType)
https://play.golang.org/p/80ZOT8_UdkG

2020-10-26 14:34 UTC, kindermoumoute submitted a review, later dismissed
LGTM

2020-10-26 14:51 UTC, Sh4d1 requested changes

2020-10-26 14:51 UTC, Sh4d1 commented on scaleway/resource_instance_server.go
> +		bootType := instance.BootType(bootType.(string))
remove this line

2020-10-26 14:54 UTC, Sh4d1 approved these changes
LGTM

2020-10-26 14:55 UTC, merged