fix(instance): ensure that tags are removed when deleted in tf
scaleway/terraform-provider-scaleway pull request #672
Opened 2020-11-02 10:57 UTC by remyleone

2020-11-06 14:45 UTC, remyleone commented
https://play.golang.org/p/uA8bWCNiTpR

2020-11-17 10:06 UTC, jerome-quere requested changes

2020-11-17 10:06 UTC, jerome-quere commented on scaleway/resource_instance_server.go
> +		if tags == nil {
func expandStrings(data interface{}) []string {
	if data == nil {
		return []string{}
	}
	stringSlice := []string{}
	for _, s := range data.([]interface{}) {
		stringSlice = append(stringSlice, s.(string))
	}
	return stringSlice
}

2020-11-20 13:19 UTC, jerome-quere approved these changes

2020-11-20 13:24 UTC, merged