chore(account): refactor data ressource workflow
scaleway/terraform-provider-scaleway pull request #680
Opened 2020-11-04 16:10 UTC by remyleone

2020-11-04 22:36 UTC, jerome-quere commented on scaleway/data_source_account_ssh_key.go
> +		Computed:     true,
Should not be marked as computed

2020-11-04 22:37 UTC, jerome-quere commented on scaleway/data_source_account_ssh_key.go
> +		ValidateFunc: validationUUIDorUUIDWithLocality(),
ssh-key are never localized

2020-11-04 22:37 UTC, jerome-quere requested changes
view comments

2020-11-09 17:18 UTC, remyleone commented
@jerome-quere do you see other resources that should be normalized?

2020-11-16 17:27 UTC, jerome-quere approved these changes

2020-11-16 17:36 UTC, merged