feat: brk make organization_id computed
scaleway/terraform-provider-scaleway pull request #746
Opened 2021-01-08 15:50 UTC by remyleone

2021-01-08 16:11 UTC, kindermoumoute requested changes

2021-01-08 16:11 UTC, kindermoumoute commented on docs/data-sources/registry_image.md
> +- `organization_id` - The ID of the organization the image is associated with.
```suggestion
- `organization_id` - The organization ID the image is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/index.md
> +Giving it a friendly-name is recommended.
We might have more links to fix here

```suggestion
need to create a new one in the section "API Keys" of the [Scaleway console](https://console.scaleway.com/project/credentials).
Click on the "Generate new API key" button to create them.
Giving it a friendly-name is recommended.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/account_ssh_key.md
> +- `organization_id` - The ID of the organization the SSH key is associated with.
```suggestion
- `organization_id` - The organization ID the SSH key is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/baremetal_server.md
> +- `organization_id` - The ID of the organization the server is associated with.
```suggestion
- `organization_id` - The organization ID the server is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_ip.md
> +- `organization_id` - The ID of the organization the IP is associated with.
```suggestion
- `organization_id` - The organization ID the IP is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_placement_group.md
> +- `organization_id` - The ID of the organization the placement group is associated with.
```suggestion
- `organization_id` - The organization ID the placement group is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_security_group.md
> +- `organization_id` - The ID of the organization the security group is associated with.
```suggestion
- `organization_id` - The organization ID the security group is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_server.md
> +- `organization_id` - The ID of the organization the server is associated with.
```suggestion
- `organization_id` - The organization ID the server is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_server.md
> +  If you intend to deploy your instance in another project than the default one use your `project_id` instead of the organization id.
this line is not required anymore

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/instance_volume.md
> +- `organization_id` - The ID of the organization the volume is associated with.
```suggestion
- `organization_id` - The organization ID the volume is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/k8s_cluster.md
> +- `organization_id` - The ID of the organization the cluster is associated with.
```suggestion
- `organization_id` - The organization ID the cluster is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/lb.md
> +- `organization_id` - The ID of the organization the load-balancer is associated with.
```suggestion
- `organization_id` - The organization ID the load-balancer is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/rdb_instance.md
> +- `organization_id` - The ID of the organization the Database Instance is associated with.
```suggestion
- `organization_id` - The organization ID the Database Instance is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/registry_namespace.md
> +- `organization_id` - The ID of the organization the namespace is associated with.
```suggestion
- `organization_id` - The organization ID the namespace is associated with.
```

2021-01-08 16:11 UTC, kindermoumoute commented on docs/resources/vpc_private_network.md
> +- `organization_id` - The ID of the organization the private network is associated with.
```suggestion
- `organization_id` - The organization ID the private network is associated with.
```

2021-01-11 12:37 UTC, QuentinBrosse commented on docs/index.md
>  ## Authentication
Maybe we should also remove the `SCW_DEFAULT_ORGANIZATION_ID` below?

2021-01-12 13:54 UTC, kindermoumoute approved these changes
LGTM

2021-01-12 14:01 UTC, merged