feat(lb): add data source for lb
scaleway/terraform-provider-scaleway pull request #760
Opened 2021-01-13 16:29 UTC by remyleone

2021-03-29 16:47 UTC, jerome-quere requested changes

2021-03-29 16:47 UTC, jerome-quere commented on scaleway/data_source_lb.go
> +	if !ok { // Get LB by region.
```suggestion
	if !ok { // Get LB by name.
```

2021-03-29 16:47 UTC, jerome-quere commented on scaleway/data_source_lb.go
> +			return diag.FromErr(fmt.Errorf("no lbs found with the address %s", d.Get("ip_address")))
```suggestion
			return diag.FromErr(fmt.Errorf("no lbs found with the name %s", d.Get("name")))
```

2021-03-29 16:47 UTC, jerome-quere commented on docs/data-sources/lb.md
> +- `type` - (Required) The type of the load-balancer.
Wrong copy/paste ?

2021-03-29 16:47 UTC, jerome-quere commented on docs/data-sources/lb.md
> +- `ip_address` - (Optional) The IP address.
Should be name ?

2021-03-29 16:50 UTC, QuentinBrosse requested changes

2021-03-29 16:50 UTC, QuentinBrosse commented on docs/data-sources/lb.md
> +  Only one of `name` and `lb_id` should be specified.
```suggestion
  Only one of `ip_address` and `lb_id` should be specified.
```

2021-03-29 16:50 UTC, QuentinBrosse commented on docs/data-sources/lb.md
> +- `lb_id` - The associated load-balance ID if any
Already in `Argument Reference` section

2021-03-30 12:53 UTC, QuentinBrosse requested changes

2021-09-16 12:26 UTC, Monitob commented on scaleway/data_source_lb.go
> +	api, region, err := lbAPIWithRegion(d, meta)
lb do not support region anymore since version 2.1.0. I'm gonna update this branch.

2021-09-16 13:58 UTC, Monitob approved these changes

2021-09-16 13:58 UTC, merged